package telas;

import java.awt.Color;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JTable;
import models.*;
import persistencia.dao.mysql.MySqlJuizDAO;
import persistencia.dao.mysql.MySqlPosicaoDAO;
import persistencia.dao.mysql.MySqlSelecaoDAO;

/**
 *
 * @author Felipe Miyazaki - Karine Antoniacomi - Ricardo Filho
 */

public class HelperList extends javax.swing.JFrame {

    Posicao posicaoFocus = null;
    Selecao selecaoFocus = null;
    List<Posicao> posicoes = new ArrayList<Posicao>();
    List<Selecao> selecoes = new ArrayList<Selecao>();
    List<Juiz> juizes = new ArrayList<Juiz>();

    /**
     * Creates new form HelperList
     */
    public HelperList(Posicao posicaoFocus) {
        this.posicaoFocus = posicaoFocus;

        initComponents();
        setVisible(true);
        renderPosicoes();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    public HelperList(List<Juiz> juizes) {
        this.juizes = juizes;

        initComponents();
        setVisible(true);
        renderJuizes();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    public HelperList(Selecao selecaoFocus, boolean cadastroTreinador) {
        this.selecaoFocus = selecaoFocus;
        MySqlSelecaoDAO dao = new MySqlSelecaoDAO(Menu.conn);
        if (cadastroTreinador) {
            selecoes = dao.listaTodosSemTreinador();

        } else {
            selecoes = dao.listaTodos();
        }

        initComponents();
        setVisible(true);
        renderSelecoes();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    public JTable getTable() {
        return this.contatoTable;
    }

    void renderJuizes() {

        MySqlJuizDAO daoJuizes = new MySqlJuizDAO(Menu.conn);

        this.juizes = daoJuizes.listaTodos();

        Object[][] jogadoresView = new Object[juizes.size()][4];
        for (int i = 0; i < juizes.size(); i++) {
            jogadoresView[i][0] = juizes.get(i).getNome();
            jogadoresView[i][1] = juizes.get(i).getData_nasc();
            jogadoresView[i][2] = juizes.get(i).getNacionalidade();

        }
        contatoTable.setModel(new javax.swing.table.DefaultTableModel(
                jogadoresView,
                new String[]{
                    "Nome", "Nascimento", "Nacionalidade"
                }
        ));

    }

    void renderSelecoes() {

        Object[][] jogadoresView = new Object[selecoes.size()][2];
        for (int i = 0; i < selecoes.size(); i++) {
            jogadoresView[i][0] = selecoes.get(i).getId();
            jogadoresView[i][1] = selecoes.get(i).getNome();

        }
        contatoTable.setModel(new javax.swing.table.DefaultTableModel(
                jogadoresView,
                new String[]{
                    "ID", "SELEÇÃO"
                }
        ));
    }

    void renderPosicoes() {

        MySqlPosicaoDAO dao = new MySqlPosicaoDAO(Menu.conn);
        posicoes = dao.listaTodos();

        Object[][] jogadoresView = new Object[posicoes.size()][2];
        for (int i = 0; i < posicoes.size(); i++) {
            jogadoresView[i][0] = posicoes.get(i).getId();
            jogadoresView[i][1] = posicoes.get(i).getNome();

        }
        contatoTable.setModel(new javax.swing.table.DefaultTableModel(
                jogadoresView,
                new String[]{
                    "Código", "Posicao"
                }
        ));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        contatoTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contatoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Title 3", "Email"
            }
        ));
        jScrollPane1.setViewportView(contatoTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable contatoTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
